project:
  type: website

website:
  title: "selinazhu"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
    right: 
      - text: CV
        href: Materials/cv.pdf

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    
execute: 
  freeze: auto
